server:
  port: 8080

spring:
  application:
    name: webflux
  main:
    web-application-type: reactive
  codec:
    max-in-memory-size: 5MB

logging:
  level:
    org.springframework.web: info

voice:
  v2:
    chunk-size: 1024
